#Q3-a: What triple with subject "CR7" and predicate "ex:speaks" was added between the two consecutive versions 'KG-2002' and 'KG-2008'?

SELECT * 
WHERE{
  ?s ?p ?o . 
  FILTER(CONTAINS(str(?p), "08"))
}
